import csv

FIELDS = (
    'PROGRAM NUMBER',
    'PROGRAM TITLE',
    'FEDERAL AGENCY',
    'MAJOR AGENCY',
    'MINOR AGENCY',
    'AUTHORIZATION',
    'OBJECTIVES',
    'TYPES OF ASSISTANCE',
    'USES AND USE RESTRICTIONS',
    'APPLICANT ELIGIBILITY',
    'BENEFICIARY ELIGIBILITY',
    'CREDENTIALS/DOCUMENTATION',
    'PREAPPLICATION COORDINATION',
    'APPLICATION PROCEDURE',
    'AWARD PROCEDURE',
    'DEADLINES',
    'RANGE OF APPROVAL/DISAPPROVAL TIME',
    'APPEALS',
    'RENEWALS',
    'FORMULA AND MATCHING REQUIREMENTS',
    'LENGTH AND TIME PHASING OF ASSISTANCE',
    'REPORTS',
    'AUDITS',
    'RECORDS',
    'ACCOUNT IDENTIFICATION',
    'OBLIGATIONS',
    'RANGE AND AVERAGE OF FINANCIAL ASSISTANCE',
    'PROGRAM ACCOMPLISHMENTS',
    'REGULATIONS, GUIDELINES, AND LITERATURE',
    'REGIONAL OR LOCAL OFFICE',
    'HEADQUARTERS OFFICE',
    'WEB SITE ADDRESS',
    'RELATED PROGRAMS',
    'EXAMPLES OF FUNDED PROJECTS',
    'CRITERIA FOR SELECTING PROPOSALS'
)

counts = {}
for f in FIELDS:
    counts[f] = 0

reader = csv.reader(open('cfda.csv','r'))
for row in reader:
    for i in range(0,len(FIELDS)):
        counts[FIELDS[i]] = max(len(row[i]), counts[FIELDS[i]])
        
for f in FIELDS:
    print '%s: %s' % (f, counts[f])
        
